- name: Create HDD mount point
  ansible.builtin.file:
    path: /mnt/hdd
    state: directory
    mode: "0755"

- name: Mount HDD
  ansible.posix.mount:
    path: /mnt/hdd
    src: /dev/sdb1
    fstype: ext4
    opts: defaults
    state: mounted

- name: Reset UFW and set defaults
  community.general.ufw:
    state: reset
    default: deny
    direction: incoming

- name: Allow full access from Local Network
  community.general.ufw:
    rule: allow
    src: 192.168.0.0/24

- name: Enable UFW
  community.general.ufw:
    state: enabled
