---
- name: Deploy Traefik
  hosts: all
  become: true

  tasks:
    - name: Create Traefik directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ apps_root }}/traefik"

    - name: Render Traefik Docker Compose file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/traefik_compose.yml.j2"
        dest: "{{ apps_root}}/traefik/compose.yml"
        mode: "0644"

    - name: Remove existing traefik container
      community.docker.docker_container:
        name: traefik
        state: absent
        force_kill: true
      ignore_errors: true

    - name: Run Traefik container
      community.docker.docker_compose_v2:
        project_src: "{{ apps_root }}/traefik"
        state: present
        recreate: always
