---
- name: Deploy Traefik
  hosts: all
  become: true

  tasks:
    - name: Create Traefik directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /opt/traefik

    - name: Fetch latest Cloudflare IPv4 list
      ansible.builtin.uri:
        url: https://www.cloudflare.com/ips-v4
        return_content: true
      register: cf_ips

    - name: Render Traefik Docker Compose file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/traefik_compose.yml.j2"
        dest: /opt/traefik/compose.yml
        mode: "0644"

    - name: Run Traefik container
      community.docker.docker_compose_v2:
        project_src: /opt/traefik
        state: present
        recreate: always
