---
- name: Configure Docker Network
  hosts: all
  become: true
  tasks:
    - name: Create tunnel network
      community.docker.docker_network:
        name: "{{ item.name }}"
        driver: bridge
        state: present
      loop:
        - { name: cf_tunnel }
        - { name: proxy }
        - { name: homepage }