---
- name: Deploy Home Server
  hosts: all
  become: true

  tasks:
    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ apps_root }}"
        state: directory
        mode: "0755"

- name: Setup Firewall
  import_playbook: playbooks/setup_firewall.yml

- name: Install Docker
  import_playbook: playbooks/install_docker.yml

- name: Set up Docker Networks
  import_playbook: playbooks/setup_docker_networks.yml

- name: Deploy Coudfare Tunnel
  import_playbook: playbooks/deploy_coludfared.yml

- name: Deploy Traefik
  import_playbook: playbooks/deploy_traefik.yml

- name: Deploy Apps
  import_playbook: playbooks/deploy_apps.yml
