- name: Create Cloudflared tunnel directory
  ansible.builtin.file:
    path: "{{ apps_root }}/cloudflared"
    state: directory
    mode: "0755"

- name: Render Cloudflared Docker Compose file
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ apps_root }}/cloudflared/compose.yml"
    mode: "0644"

- name: Run Cloudflared container
  community.docker.docker_compose_v2:
    project_src: "{{ apps_root }}/cloudflared"
    state: present
    recreate: always
